name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2

      - name: Setup Node@v18
        uses: actions/setup-node@v2
        with:
          cache: npm
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run linter
        run: npm run build
